{% set name = "kedro-vertexai" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kedro_vertexai-{{ version }}.tar.gz
  sha256: 70e9ee939dee1b53cb88a50c9c1cc020b5b3f5e66b29e1f398c6014b7d24dd97

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - python >=3.8,<3.11
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8,<3.11
    - kedro >=0.18.12,<0.19.0
    - click >=8.0.4
    - kfp >=1.3.0,<2.0
    - kfp-server-api >=1.4.0,<2.0 # Packages found in the meta.yaml but not found by source code inspection:
    #- kfp-pipeline-spec #Not in requirements https://github.com/getindata/kedro-vertexai/blob/develop/pyproject.toml#L34
    - tabulate >=0.8.7
    - semver >=2.10,<4.0.0 # Packages found in the meta.yaml but not found by source code inspection:
    - pydantic >=1.9.0,<2.0.0
    - google-auth <3 # Packages found in the meta.yaml but not found by source code inspection:
    - google-cloud-scheduler >=2.3.2 # Packages found in the meta.yaml but not found by source code inspection:
    - google-cloud-iam <3 # Packages found in the meta.yaml but not found by source code inspection:
    - gcsfs >=2022.1 # Packages found in the meta.yaml but not found by source code inspection:
    - fsspec >=2022.1
    - google-cloud-storage <3.0.0 # Packages found in the meta.yaml but not found by source code inspection:
    - grpcio >=1.4.0,<2.0.0 # Packages found in the meta.yaml but not found by source code inspection:
    - grpcio-status >=1.4.0,<2.0.0 # Packages found in the meta.yaml but not found by source code inspection:
    - protobuf >=3.9.0,<21.0 # Packages found in the meta.yaml but not found by source code inspection:
    - cachetools >=3.0,<6.0
# Packages found by source code inspection but not in the meta.yaml:
    #- cloudpickle
    #- pluggy
    #- requests
    #- omegaconf
    #- pyyaml
  run_constrained:
    - kedro-mlflow >=0.11.8,<0.12.0

test:
  imports:
    - kedro_vertexai
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/getindata/kedro-vertexai
  summary: Kedro plugin with GCP Vertex AI support
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cshaley
    - zaigner
    - millsks
    - rxm7706
