{% set name = "kedro-vertexai" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kedro_vertexai-{{ version }}.tar.gz
  sha256: 9567365d4ab652fa8e0acf1363c00d87aa5a7500449757a8eb37e27601682938

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - python >=3.7,<3.11
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.7,<3.11
    - kedro >=0.18.8,<0.19.0
    - click >=8.0.4
    - kfp >=1.4.0,<2.0
    - kfp-server-api >=1.4.0,<2.0
    - tabulate >=0.8.7
    - semver >=2.10.0,<3.0.0
    - pydantic >=1.9.0,<2.0.0
    - google-auth <3.0.0
    - google-cloud-scheduler <3.0.0
    - google-cloud-iam <3.0.0
    - gcsfs >=2022.1
    - fsspec >=2022.1
    - google-cloud-storage <3.0.0
    - grpcio >=1.4.0,<1.60.0
    - grpcio-status >=1.4.0,<1.60.0
    - protobuf >=3.18.0,<21.0
    - cachetools >=3.0,<6.0
  run_constrained:
    - kedro-mlflow >=0.11.8,<0.12.0

test:
  imports:
    - kedro_vertexai
  #commands:
    #- pip check
  requires:
    - pip

about:
  home: https://github.com/getindata/kedro-vertexai
  summary: Kedro plugin with GCP Vertex AI support
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cshaley
    - zaigner
    - millsks
    - rxm7706
